### ISSUE TITLE
Find a proper error message in case of unauthorization

### ISSUE THREAD

**Issue by smic1909** [zalando-stups/kio-cli#5]
It would be nice to have a meaningful error message in case of unauthorization.

`bash kio applications
Traceback (most recent call last):
  File "/usr/local/bin/kio", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/kio/cli.py", line 240, in main
    cli()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/kio/cli.py", line 92, in applications
    r.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://kio.stups.zalan.do/apps`

**Comment by harti2006** [comment]
Since this ticket is quite old and hard to reproduce (I actually had to modify the tokens in `ztoken` store manually) I would like to close that issue. Feel free to open again if this still bugs you a lot.
